# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Weekly schedule',
                'verbose_name_plural': 'Weekly schedules',
            },
        ),
        migrations.CreateModel(
            name='WorkingBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], verbose_name='Weekday')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('weekly_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.WeeklySchedule', verbose_name='Weekly schedule')),
            ],
            options={
                'verbose_name': 'Working block',
                'verbose_name_plural': 'Working blocks',
            },
        ),
    ]
